name: Run the OSS review tool

inputs:
    folder_path:
        description: "The root folder to run the ORT tool from"
        required: true
        type: string
    config_file:
        description: "ORT configuration file to use"
        required: false
        type: string
        default: "config.yml"

runs:
    using: "composite"
    steps:
        - name: Run ORT tools
          id: ort
          working-directory: ./ort/
          shell: bash
          env:
              FOLDER: ${{ inputs.folder_path }}
              CONFIG_FILE: ${{ inputs.config_file }}
          run: |
              echo "Running ORT tools for $FOLDER with config $CONFIG_FILE"
              # Calculate relative path from workspace root
              RELATIVE_PATH=$(realpath --relative-to="$GITHUB_WORKSPACE" "$FOLDER")
              echo "RELATIVE_PATH=$RELATIVE_PATH" >> "$GITHUB_OUTPUT"
              echo "LOCAL_PATH=`basename $FOLDER`" >> "$GITHUB_OUTPUT"
              mkdir $FOLDER/ort_results
              # Analyzer (analyzer-result.json)
              ./gradlew cli:run --args="--info analyze -c ~/.ort/config/$CONFIG_FILE -i $FOLDER -o $FOLDER/ort_results -f JSON"

              # NOTICE DEFAULT
              ./gradlew cli:run --args="--info report -i $FOLDER/ort_results/analyzer-result.json -o $FOLDER/ort_results/ -f PlainTextTemplate"

        - name: Upload ORT results
          if: always()
          continue-on-error: true
          uses: actions/upload-artifact@v4
          with:
              name: ort_results-${{ steps.ort.outputs.LOCAL_PATH }}
              path: |
                  ${{ steps.ort.outputs.RELATIVE_PATH }}/ort_results/**
